spring:
  application:
    name: example-service
  datasource:
    url: 'jdbc:postgresql://localhost:5432/crud_database'
    username: myuser
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 7898
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka