spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/crud_database'
    username: myuser
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none